/**
 * Hook de autocorrección para español.
 * 
 * Corrige automáticamente errores ortográficos comunes al escribir,
 * activándose cuando se presiona espacio, punto, coma u otro separador.
 * Similar a la autocorrección de un teclado de celular.
 */

// ─── Diccionario de correcciones ────────────────────────────────────────────
// Formato: 'error' => 'corrección'
// Solo incluye correcciones INEQUÍVOCAS para evitar falsos positivos.

const CORRECTIONS: Record<string, string> = {
    // ── Tildes omitidas (palabras inequívocas) ──────────────────
    'tambien': 'también',
    'tambn': 'también',
    'ademas': 'además',
    'despues': 'después',
    'aqui': 'aquí',
    'ahi': 'ahí',
    'asi': 'así',
    'atras': 'atrás',
    'detras': 'detrás',
    'quiza': 'quizá',
    'quizas': 'quizás',
    'dificil': 'difícil',
    'facil': 'fácil',
    'rapido': 'rápido',
    'rapida': 'rápida',
    'rapidos': 'rápidos',
    'rapidas': 'rápidas',
    'rapidamente': 'rápidamente',
    'ultimo': 'último',
    'ultima': 'última',
    'ultimos': 'últimos',
    'ultimas': 'últimas',
    'proximo': 'próximo',
    'proxima': 'próxima',
    'proximos': 'próximos',
    'proximas': 'próximas',
    'sabado': 'sábado',
    'sabados': 'sábados',
    'miercoles': 'miércoles',
    'numero': 'número',
    'numeros': 'números',
    'telefono': 'teléfono',
    'telefonos': 'teléfonos',
    'informacion': 'información',
    'atencion': 'atención',
    'comunicacion': 'comunicación',
    'confirmacion': 'confirmación',
    'situacion': 'situación',
    'operacion': 'operación',
    'solucion': 'solución',
    'direccion': 'dirección',
    'ubicacion': 'ubicación',
    'explicacion': 'explicación',
    'aplicacion': 'aplicación',
    'configuracion': 'configuración',
    'notificacion': 'notificación',
    'habitacion': 'habitación',
    'reservacion': 'reservación',
    'cancelacion': 'cancelación',
    'facturacion': 'facturación',
    'evaluacion': 'evaluación',
    'calificacion': 'calificación',
    'condicion': 'condición',
    'promocion': 'promoción',
    'educacion': 'educación',
    'relacion': 'relación',
    'funcion': 'función',
    'opcion': 'opción',
    'eleccion': 'elección',
    'sesion': 'sesión',
    'version': 'versión',
    'comision': 'comisión',
    'decision': 'decisión',
    'revision': 'revisión',
    'precision': 'precisión',
    'television': 'televisión',
    'conexion': 'conexión',
    'razon': 'razón',
    'corazon': 'corazón',
    'cancion': 'canción',
    'accion': 'acción',
    'seccion': 'sección',
    'leccion': 'lección',
    'recepcion': 'recepción',
    'coleccion': 'colección',
    'produccion': 'producción',
    'construccion': 'construcción',
    'instruccion': 'instrucción',
    'destruccion': 'destrucción',
    'proteccion': 'protección',
    'inspeccion': 'inspección',
    'correccion': 'corrección',
    'seleccion': 'selección',
    'perfeccion': 'perfección',
    'satisfaccion': 'satisfacción',
    'transaccion': 'transacción',
    'reaccion': 'reacción',
    'interaccion': 'interacción',
    'podria': 'podría',
    'tendria': 'tendría',
    'vendria': 'vendría',
    'diria': 'diría',
    'haria': 'haría',
    'sabria': 'sabría',
    'saldria': 'saldría',
    'pondria': 'pondría',
    'deberia': 'debería',
    'querria': 'querría',
    'podriamos': 'podríamos',
    'deberiamos': 'deberíamos',
    'hariamos': 'haríamos',
    'estariamos': 'estaríamos',
    // 'seria' omitida - puede ser adjetivo "seria" (serious)
    'podrian': 'podrían',
    'deberian': 'deberían',
    'harian': 'harían',
    'estarian': 'estarían',
    'serian': 'serían',
    'tendrian': 'tendrían',
    'todavia': 'todavía',
    'dia': 'día',
    'dias': 'días',
    'guia': 'guía',
    'categoria': 'categoría',
    'garantia': 'garantía',
    'compañia': 'compañía',
    'mercancia': 'mercancía',
    'policia': 'policía',
    'energia': 'energía',
    'tecnologia': 'tecnología',
    'economia': 'economía',
    'teoria': 'teoría',
    'fotografia': 'fotografía',
    'pagina': 'página',
    'paginas': 'páginas',
    'codigo': 'código',
    'articulo': 'artículo',
    'articulos': 'artículos',
    'vehiculo': 'vehículo',
    'vehiculos': 'vehículos',
    'periodo': 'período',
    'metodo': 'método',
    'credito': 'crédito',
    'creditos': 'créditos',
    'debito': 'débito',
    'deposito': 'depósito',
    'proposito': 'propósito',
    'exito': 'éxito',
    'habito': 'hábito',
    'transito': 'tránsito',
    'publico': 'público',
    'publica': 'pública',
    'musica': 'música',
    'medico': 'médico',
    'medica': 'médica',
    'tecnico': 'técnico',
    'tecnica': 'técnica',
    'clasico': 'clásico',
    'clasica': 'clásica',
    'practico': 'práctico',
    'practica': 'práctica',
    'automatico': 'automático',
    'automatica': 'automática',
    'electronico': 'electrónico',
    'electronica': 'electrónica',
    'economico': 'económico',
    'economica': 'económica',
    'historico': 'histórico',
    'historica': 'histórica',
    'especifico': 'específico',
    'especifica': 'específica',
    'basico': 'básico',
    'basica': 'básica',
    'logico': 'lógico',
    'logica': 'lógica',
    'unico': 'único',
    'unica': 'única',
    'minimo': 'mínimo',
    'minima': 'mínima',
    'maximo': 'máximo',
    'maxima': 'máxima',
    'valido': 'válido',
    'valida': 'válida',
    'comodo': 'cómodo',
    'comoda': 'cómoda',
    'perdida': 'pérdida',
    'pelicula': 'película',
    'peliculas': 'películas',
    'maquina': 'máquina',
    'maquinas': 'máquinas',
    'fabrica': 'fábrica',
    'lampara': 'lámpara',
    'camara': 'cámara',
    'camaras': 'cámaras',
    'sabana': 'sábana',
    'platano': 'plátano',
    'pajaro': 'pájaro',
    'arbol': 'árbol',
    'arboles': 'árboles',
    'angel': 'ángel',
    'angeles': 'ángeles',
    'carcel': 'cárcel',
    'cesped': 'césped',
    'huesped': 'huésped',
    'portatil': 'portátil',
    'movil': 'móvil',
    'util': 'útil',
    'fragil': 'frágil',
    'debil': 'débil',
    'agil': 'ágil',
    'fertil': 'fértil',
    'esteril': 'estéril',
    'volatil': 'volátil',
    'automaticamente': 'automáticamente',
    'especificamente': 'específicamente',
    'basicamente': 'básicamente',
    'tecnicamente': 'técnicamente',
    'practicamente': 'prácticamente',
    'logicamente': 'lógicamente',
    'economicamente': 'económicamente',
    'unicamente': 'únicamente',
    'facilmente': 'fácilmente',
    'dificilmente': 'difícilmente',
    'comunmente': 'comúnmente',
    'tipicamente': 'típicamente',
    'ultimamente': 'últimamente',
    'proximamente': 'próximamente',
    'historicamente': 'históricamente',
    'matematicas': 'matemáticas',
    'gramatica': 'gramática',
    'ceramica': 'cerámica',
    'botanica': 'botánica',
    'mecanica': 'mecánica',
    'dinamica': 'dinámica',
    'informatica': 'informática',
    'linguistica': 'lingüística',
    'estetica': 'estética',
    'estadistica': 'estadística',
    'aritmetica': 'aritmética',
    'geometria': 'geometría',
    'geografia': 'geografía',
    'biologia': 'biología',
    'sociologia': 'sociología',
    'psicologia': 'psicología',
    'filosofia': 'filosofía',
    'astronomia': 'astronomía',
    'ingenieria': 'ingeniería',

    // ── Palabras interrogativas/exclamativas ──────────────────
    // NOTA: No se corrigen "que", "como", "cuando", "donde", "porque", etc.
    // porque dependen del contexto (interrogativo vs. relativo/causal).
    // Solo corregimos las que son inequívocas:

    // ── Errores ortográficos comunes ──────────────────────────
    'atravez': 'a través',
    'atraves': 'a través',
    'atrave': 'a través',
    'osea': 'o sea',
    'enserio': 'en serio',
    'envez': 'en vez',
    'talvez': 'tal vez',
    'almenos': 'al menos',
    'porfavor': 'por favor',
    'porfabor': 'por favor',
    'porfis': 'por favor',
    'porfa': 'por favor',
    'porfas': 'por favor',
    'porfavar': 'por favor',
    'porfvor': 'por favor',
    'deverdad': 'de verdad',
    'deacuerdo': 'de acuerdo',
    'dacuerdo': 'de acuerdo',
    'sobretodo': 'sobre todo',
    'enparte': 'en parte',
    'infin': 'en fin',
    'enmedio': 'en medio',
    'encontra': 'en contra',
    'devez': 'de vez',
    'encuanto': 'en cuanto',
    'amenudo': 'a menudo',
    'derepente': 'de repente',
    'derrepente': 'de repente',
    'demaciado': 'demasiado',
    'demaciada': 'demasiada',
    'demaciados': 'demasiados',
    'demaciadas': 'demasiadas',
    'nesesario': 'necesario',
    'nesesaria': 'necesaria',
    'nesecario': 'necesario',
    'nesecitar': 'necesitar',
    'nesesitar': 'necesitar',
    'nesecito': 'necesito',
    'nesesito': 'necesito',
    'nesecita': 'necesita',
    'nesesita': 'necesita',
    'nesecitamos': 'necesitamos',
    'nesesitamos': 'necesitamos',
    'nesesitan': 'necesitan',
    'nesecitan': 'necesitan',
    'exelente': 'excelente',
    'exelentes': 'excelentes',
    'exsacto': 'exacto',
    'exsacta': 'exacta',
    'exsactamente': 'exactamente',
    'exsiste': 'existe',
    'exsistir': 'existir',
    'exijir': 'exigir',
    'recivir': 'recibir',
    'recivido': 'recibido',
    'recivida': 'recibida',
    'resivir': 'recibir',
    'resivido': 'recibido',
    'recivi': 'recibí',
    'recojido': 'recogido',
    'recojer': 'recoger',
    'protejer': 'proteger',
    'dirijir': 'dirigir',
    'correjir': 'corregir',
    'correjido': 'corregido',
    'elejir': 'elegir',
    'surjir': 'surgir',
    'preveer': 'prever',
    'haver': 'haber',
    'aver': 'a ver',
    'aber': 'haber',
    'aserca': 'acerca',
    'aserka': 'acerca',
    'hize': 'hice',
    'hise': 'hice',
    'hiso': 'hizo',
    'ise': 'hice',
    'iso': 'hizo',
    'hasemos': 'hacemos',
    'hasiendo': 'haciendo',
    'halluda': 'ayuda',
    'ayueda': 'ayuda',
    'hallua': 'ayuda',
    'lla': 'ya',
    'yama': 'llama',
    'yamada': 'llamada',
    'yamar': 'llamar',
    'yamamos': 'llamamos',
    'yamo': 'llamó',
    'yave': 'llave',
    'yuvia': 'lluvia',
    'yegar': 'llegar',
    'yego': 'llegó',
    'yegamos': 'llegamos',
    'yeno': 'lleno',
    'yena': 'llena',
    'yenar': 'llenar',
    'yevar': 'llevar',
    'yevamos': 'llevamos',
    'yevo': 'llevó',
    'travez': 'través',
    'travéz': 'través',
    'ahy': 'ahí',
    'hai': 'hay',
    'horita': 'ahorita',
    'haora': 'ahora',
    'aora': 'ahora',
    'haiga': 'haya',
    'hubieron': 'hubo',
    'nadien': 'nadie',
    'naiden': 'nadie',
    'trompesar': 'tropezar',
    'empesar': 'empezar',
    'empeze': 'empecé',
    'empezo': 'empezó',
    'comensar': 'comenzar',
    'comense': 'comencé',
    'comenso': 'comenzó',
    'conoser': 'conocer',
    'reconoser': 'reconocer',
    'conosco': 'conozco',
    'produsir': 'producir',
    'produsco': 'produzco',
    'traducsion': 'traducción',
    'tradusir': 'traducir',
    'conducsion': 'conducción',
    'condusir': 'conducir',
    'reducsion': 'reducción',
    'redusir': 'reducir',
    'desir': 'decir',
    'dise': 'dice',
    'disen': 'dicen',
    'disiendo': 'diciendo',
    'discuple': 'disculpe',
    'discupla': 'disculpa',
    'vuenas': 'buenas',
    'buno': 'bueno',
    'benas': 'buenas',
    'vien': 'bien',
    'bie': 'bien',
    'bn': 'bien',
    'pdo': 'puedo',
    'pedo': 'puedo',
    'muxo': 'mucho',
    'muxos': 'muchos',
    'muxa': 'mucha',
    'muxas': 'muchas',
    'grasias': 'gracias',
    'grcias': 'gracias',
    'grasia': 'gracia',
    'gacias': 'gracias',
    'grazias': 'gracias',
    'grasas': 'gracias',
    'gracas': 'gracias',
    'perdoneme': 'perdóneme',
    'perdon': 'perdón',
    'disculpeme': 'discúlpeme',
    'xq': 'por qué',
    'xk': 'por qué',
    'xfa': 'por favor',
    'xfavor': 'por favor',
    'tmb': 'también',
    'tb': 'también',
    'tbm': 'también',
    'tmbn': 'también',
    'msj': 'mensaje',
    'msg': 'mensaje',
    'msgs': 'mensajes',
    'msjs': 'mensajes',
    'inf': 'información',
    'info': 'información',
    'fvr': 'favor',
    'cel': 'celular',
    'tel': 'teléfono',
    'desp': 'después',
    'dsp': 'después',
    'dps': 'después',
    'resp': 'respuesta',
    'aprox': 'aproximadamente',

    // ── B/V confusiones comunes ──────────────────────────────
    'iva': 'iba',
    'ivamos': 'íbamos',
    'ivan': 'iban',
    'tubo': 'tuvo', // context dependent but more common as verb
    'tubimos': 'tuvimos',
    'tubieron': 'tuvieron',
    'tube': 'tuve',
    'estubo': 'estuvo',
    'estube': 'estuve',
    'estubimos': 'estuvimos',
    'estubieron': 'estuvieron',
    'andube': 'anduve',
    'andubo': 'anduvo',
    'suve': 'sube',
    'bamos': 'vamos',
    'biene': 'viene',
    'bienen': 'vienen',
    'benido': 'venido',
    'benir': 'venir',
    'ber': 'ver',
    'berdad': 'verdad',
    'berdadero': 'verdadero',
    'biaje': 'viaje',
    'biajar': 'viajar',
    'biejo': 'viejo',
    'bieja': 'vieja',
    'bida': 'vida',
    'vibir': 'vivir',
    'bibo': 'vivo',
    'biba': 'viva',
    'bibir': 'vivir',
    'bolber': 'volver',
    'bolver': 'volver',
    'bolbi': 'volví',
    'bolbio': 'volvió',
    'bolbimos': 'volvimos',

    // ── S/C/Z confusiones ────────────────────────────────────
    'conosemos': 'conocemos',
    'conosido': 'conocido',
    'haser': 'hacer',
    'asertar': 'acertar',
    'sapato': 'zapato',
    'sapatos': 'zapatos',
    'sinco': 'cinco',
    'sena': 'cena',
    'senar': 'cenar',
    'serca': 'cerca',
    'sercano': 'cercano',
    'sercana': 'cercana',
    'serrar': 'cerrar',
    'serrado': 'cerrado',
    'serrada': 'cerrada',
    'siego': 'ciego',
    'siega': 'ciega',
    'sielo': 'cielo',
    'sien': 'cien',
    'siento': 'ciento',
    'sierto': 'cierto',
    'sierta': 'cierta',
    'sinema': 'cinema',
    'sircular': 'circular',
    'sircunstancia': 'circunstancia',
    'siudad': 'ciudad',
    'sivil': 'civil',
    'conseder': 'conceder',
    'consequencia': 'consecuencia',
    'consequencias': 'consecuencias',

    // ── Palabras de uso frecuente en atención al cliente ──────
    'envio': 'envío',
    'envios': 'envíos',
    'reclamacion': 'reclamación',
    'devolucion': 'devolución',
    'catalogo': 'catálogo',
    'catalogos': 'catálogos',
    'disponoble': 'disponible',
    'disponivle': 'disponible',
    'disponble': 'disponible',
    'dispponible': 'disponible',
    'dispinible': 'disponible',
    'verificacion': 'verificación',
    'berificar': 'verificar',
    'berificacion': 'verificación',
    'inconbeniente': 'inconveniente',
    'inconbenientes': 'inconvenientes',
    'agradesco': 'agradezco',

    // ── Saludos y frases comunes ─────────────────────────────
    'bienbenido': 'bienvenido',
    'bienbenida': 'bienvenida',
    'bienbenidos': 'bienvenidos',
    'bienbenidas': 'bienvenidas',
    'bienvinido': 'bienvenido',
    'bienvinida': 'bienvenida',
    'biemvenido': 'bienvenido',
    'biemvenida': 'bienvenida',
    'felisidades': 'felicidades',
    'felizidades': 'felicidades',
    'feliidades': 'felicidades',
    'discuplas': 'disculpas',
    'lamentablmente': 'lamentablemente',
    'desafortunadamnete': 'desafortunadamente',

    // ── Abreviaciones de chat que expanden ───────────────────
    'pa': 'para',
    'pal': 'para el',
    'tonces': 'entonces',
    'ntonces': 'entonces',
    'entonce': 'entonces',
    'entonses': 'entonces',
    'entocnes': 'entonces',
    'entoncs': 'entonces',
    'ps': 'pues',
    'pos': 'pues',

    // ── Errores de tipeo frecuentes ──────────────────────────
    'tegnologia': 'tecnología',
    'tegnologico': 'tecnológico',
    'tegnologica': 'tecnológica',
    'calidd': 'calidad',
    'caliddad': 'calidad',
    'calidda': 'calidad',
    'probelma': 'problema',
    'probelmas': 'problemas',
    'porblema': 'problema',
    'porblemas': 'problemas',
    'prolbema': 'problema',
    'prolbemas': 'problemas',
    'problmea': 'problema',
    'preocupasion': 'preocupación',
    'preocupacion': 'preocupación',
    'seguriddad': 'seguridad',
    'seguirdad': 'seguridad',
    'seguiridad': 'seguridad',
    'seguriadad': 'seguridad',
    'imporatnte': 'importante',
    'improtante': 'importante',
    'impotante': 'importante',
    'importnate': 'importante',
    'importatne': 'importante',
    'priemro': 'primero',
    'premiro': 'primero',
    'tiepo': 'tiempo',
    'tiemp': 'tiempo',
    'tiepmo': 'tiempo',
    'tiemppo': 'tiempo',
    'emopmento': 'momento',
    'moemento': 'momento',
    'moemtno': 'momento',
    'mometno': 'momento',
    'momeno': 'momento',
    'moemnto': 'momento',
    'porfvaor': 'por favor',
    'favo': 'favor',
    'favro': 'favor',
    'muhas': 'muchas',
    'muhcas': 'muchas',
    'mhucas': 'muchas',
    'muhco': 'mucho',
    'muhcos': 'muchos',
    'muhca': 'mucha',
    'graiacs': 'gracias',
    'grcaias': 'gracias',
    'gracs': 'gracias',
    'graicais': 'gracias',
    'estimaod': 'estimado',
    'estimaoda': 'estimada',
    'estimdao': 'estimado',
    'estimdaa': 'estimada',
    'cordialmetne': 'cordialmente',
    'cordialmnete': 'cordialmente',
    'cordail': 'cordial',
    'atenatmente': 'atentamente',
    'atentamtne': 'atentamente',
    'atentametn': 'atentamente',
    'atenntamente': 'atentamente',
    'antetamente': 'atentamente',
    'pesonalmente': 'personalmente',
    'personalmtne': 'personalmente',

    // ── Más correcciones de uso diario ────────────────────────
    'nmoche': 'noche',
    'anoceh': 'anoche',
    'mañaan': 'mañana',
    'manaña': 'mañana',
    'manana': 'mañana',
    'semaan': 'semana',
    'semantica': 'semántica',
    'veernes': 'viernes',
    'vienres': 'viernes',
    'domigno': 'domingo',
    'domigon': 'domingo',
    'feberero': 'febrero',
    'febreo': 'febrero',
    'mrazo': 'marzo',
    'abirl': 'abril',
    'junnio': 'junio',
    'juilo': 'julio',
    'agosot': 'agosto',
    'septiemrbe': 'septiembre',
    'septimebre': 'septiembre',
    'ocutbre': 'octubre',
    'novimebre': 'noviembre',
    'noviemrbe': 'noviembre',
    'dicimebre': 'diciembre',
    'diciemrbe': 'diciembre',
};

// ─── Palabras que NO deben corregirse (para evitar falsos positivos) ─────
// Estas se chequean primero; si la palabra está aquí, no se toca.
const EXCEPTIONS = new Set([
    // Letras sueltas comunes en el contexto (no corregir "x" si va sola en ciertos contextos)
    // ... podemos agregar según se necesite
    'ok', 'OK', 'Ok',
    'no', 'si', 'yo', 'tu', 'el', 'la', 'lo', 'un', 'en', 'es', 'ya',
    'al', 'de', 'se', 'me', 'le', 'te', 'ni', 'mi',
    'jaja', 'jajaja', 'jeje', 'jejeje',
    'hmm', 'mmm', 'uhm', 'ah', 'oh',
]);

// ─── Lógica de corrección ─────────────────────────────────────────────────

/**
 * Corrige una sola palabra según el diccionario.
 * Preserva la capitalización original.
 */
function correctWord(word: string): string | null {
    if (!word || word.length < 2) return null;
    
    // No corregir palabras que empiecen con / (comandos de plantilla)
    if (word.startsWith('/')) return null;
    
    // No corregir URLs
    if (word.includes('http') || word.includes('www.') || word.includes('.com')) return null;
    
    // No corregir emails
    if (word.includes('@')) return null;
    
    // No corregir números (puros o con formato)
    if (/^\d+([.,]\d+)*$/.test(word)) return null;
    
    // No corregir excepciones
    if (EXCEPTIONS.has(word)) return null;

    const lowerWord = word.toLowerCase();
    
    // No corregir excepciones (case-insensitive)
    if (EXCEPTIONS.has(lowerWord)) return null;

    const correction = CORRECTIONS[lowerWord];
    if (!correction || correction === lowerWord) return null;

    // Preservar capitalización
    if (word === word.toUpperCase() && word.length > 1) {
        // TODO MAYÚSCULAS -> CORRECCIÓN EN MAYÚSCULAS
        return correction.toUpperCase();
    }
    if (word[0] === word[0].toUpperCase() && word.slice(1) === word.slice(1).toLowerCase()) {
        // Primera mayúscula -> Capitalizar corrección
        return correction.charAt(0).toUpperCase() + correction.slice(1);
    }
    
    return correction;
}

/**
 * Procesa un texto y corrige la última palabra escrita
 * cuando se detecta un separador (espacio, punto, coma, etc.)
 * 
 * @param text - El texto completo del input
 * @param previousText - El texto anterior (para detectar si se acaba de escribir un separador)
 * @returns { correctedText, wasChanged, original, corrected } 
 */
export function autoCorrectText(text: string, previousText: string): {
    correctedText: string;
    wasChanged: boolean;
    original: string;
    corrected: string;
} {
    const noChange = { correctedText: text, wasChanged: false, original: '', corrected: '' };
    
    if (!text || text.length < 2) return noChange;
    
    // Solo actuar cuando se acaba de escribir un separador
    const lastChar = text[text.length - 1];
    const separators = [' ', '.', ',', ';', ':', '!', '?', '\n', ')'];
    
    if (!separators.includes(lastChar)) return noChange;
    
    // Extraer la última palabra (antes del separador)
    const textBeforeSep = text.slice(0, -1);
    
    // Encontrar dónde empieza la última palabra
    const lastSepIndex = Math.max(
        textBeforeSep.lastIndexOf(' '),
        textBeforeSep.lastIndexOf('\n'),
        textBeforeSep.lastIndexOf('.'),
        textBeforeSep.lastIndexOf(','),
        textBeforeSep.lastIndexOf(';'),
        textBeforeSep.lastIndexOf(':'),
        textBeforeSep.lastIndexOf('!'),
        textBeforeSep.lastIndexOf('?'),
        textBeforeSep.lastIndexOf('('),
        textBeforeSep.lastIndexOf(')'),
    );
    
    const wordStart = lastSepIndex + 1;
    const lastWord = textBeforeSep.slice(wordStart);
    
    if (!lastWord) return noChange;
    
    const correction = correctWord(lastWord);
    if (!correction) return noChange;
    
    // Reconstruir el texto con la corrección
    const correctedText = text.slice(0, wordStart) + correction + lastChar;
    
    return {
        correctedText,
        wasChanged: true,
        original: lastWord,
        corrected: correction,
    };
}

// ─── Estadísticas para feedback sutil ─────────────────────────────────────

export interface CorrectionEvent {
    original: string;
    corrected: string;
    timestamp: number;
}
